copying azure deve to master

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,20 +1,164 @@
-pool:
-  vmImage: 'Ubuntu 16.04'
+#########################################################################################
+# DataSHIELD Azure test suite - dsBase.
+# Starts with a vanilla Ubuntu VM, installs R then does devtools::checks()
+# Inside the root directory $(Pipeline.Workspace) will be a file tree like:
+# /dsBase               <- Checked out version of datashield/dsBase
+#
+# As of May 2020 this takes ~ 20 mins to run.
+#
+# Nothing should ever need changing in this as the repo will always check itself out.
+#
+#########################################################################################
 
-steps:
-- bash: |
-    sudo apt-get update
-    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
-    sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
-    sudo apt-get update
-    sudo apt-get install -qq libxml2-dev libcurl4-openssl-dev libssl-dev -y
-    sudo apt-get install -qq r-base -y
-    sudo R -e "install.packages('devtools', dependencies=TRUE)"
-    sudo R -e "install.packages('RANN', dependencies=TRUE)"
-  displayName: 'Install R Client'
 
-- bash: |
-    R -e "library('devtools'); devtools::check(args = c('--no-examples'))" | tee azure-pipelines_check.Rout
-    grep --quiet "^0 errors" azure-pipelines_check.Rout && grep --quiet " 0 warnings" azure-pipelines_check.Rout && grep --quiet " 0 notes" azure-pipelines_check.Rout
-  displayName: 'Devtools checks'
-  condition: always()
+#########################################################################################
+# When and under what condition to run the pipeline.
+schedules:
+  - cron: "32 1 * * *"
+    displayName: Nightly build
+    branches:
+     include:
+      - master
+    always: true
+
+jobs:
+- job: run_devtools_check
+  timeoutInMinutes: 30
+  pool:
+    vmImage: 'Ubuntu 16.04'
+
+
+  steps:
+    #####################################################################################
+    # Checkout the source code to a subfolder.
+    # This may give an error in the logs like:
+    # [warning]Unable move and reuse existing repository to required location
+    # This is an Azure bug - https://github.com/microsoft/azure-pipelines-yaml/issues/403
+  - checkout: self
+    path: 'dsBase'
+
+
+    #####################################################################################
+    # The Azure VMs have 2 CPUs, so configure R to use both when compile/install packages.
+    # If previous steps have failed then don't run.
+  - bash: |
+
+      echo "options(Ncpus=2)" >> ~/.Rprofile
+
+    displayName: 'Tweak local R env using .Rprofile'
+    condition: succeeded()
+
+
+    #####################################################################################
+    # Install R and all the dependencies dsBase requires.
+    # If previous steps have failed then don't run.
+  - bash: |
+      
+      sudo apt-get update
+      sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
+      sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/'
+      sudo apt-get update
+      sudo apt-get install -qq libxml2-dev libcurl4-openssl-dev libssl-dev -y
+      sudo apt-get install -qq r-base -y
+      sudo R -e "install.packages('devtools', dependencies=TRUE)"
+      sudo R -e "install.packages('RANN', dependencies=TRUE)"
+      sudo R -e "install.packages('nlme', dependencies=TRUE)"
+      sudo R -e "install.packages('lme4', dependencies=TRUE)"
+
+    displayName: 'Install all dependencies for dsBase'
+    condition: succeeded()
+
+
+    #####################################################################################
+    # Check that the man files in the repo match what is in the function headers. i.e. has
+    # devtools::document() been run before commiting?
+    # If previous steps have failed then don't run.
+    # If this step fails still mark as failed, but don't stop the rest of the steps running.
+  - bash: |
+
+      # Concatenate all the files in the man dir into one long string and md5sum it.
+      orig_sum=$(find man -type f | sort -u | xargs cat | md5sum)
+
+      # Rebuild the documentation.
+      R -e "devtools::document()"
+
+      # Concatenate all the files in the man dir into one long string and md5sum it.
+      new_sum=$(find man -type f | sort -u | xargs cat | md5sum)
+
+      if [ "$orig_sum" != "$new_sum" ]; then
+        echo "Your committed manual files (man/*.Rd) are out of sync with the documentation in the R files."
+        echo "Run devtools::document() locally then commit again."
+        exit 1
+      else
+       echo "Documentation up to date."
+       exit 0
+      fi
+      
+    workingDirectory: $(Pipeline.Workspace)/dsBase
+    displayName: 'Check manual updated before being committed'
+    condition: succeeded()
+    continueOnError: true
+
+
+    #####################################################################################
+    # Run devtools::check on the checked out source code. 
+    # If previous steps have failed then don't run.
+    # If this step fails still mark as failed, but don't stop the rest of the steps running.    
+  - bash: |
+  
+      R -q -e "library('devtools'); devtools::check(args = c('--no-examples'))" | tee azure-pipelines_check.Rout
+      grep --quiet "^0 errors" azure-pipelines_check.Rout && grep --quiet " 0 warnings" azure-pipelines_check.Rout && grep --quiet " 0 notes" azure-pipelines_check.Rout
+
+    workingDirectory: $(Pipeline.Workspace)/dsBase
+    displayName: 'Devtools checks'
+    condition: succeeded()
+    continueOnError: true
+
+
+
+    #####################################################################################
+    # Output the environment information to the console. This is useful for debugging.
+    # Always do this, even if some of the above has failed or the job has been cacelled.
+  - bash: | 
+      
+      echo -e "\n#############################"
+      echo -e "ls /: ######################"
+      ls $(Pipeline.Workspace)
+    
+      echo -e "\n#############################"
+      echo -e "lscpu: ######################"
+      lscpu
+      
+      echo -e "\n#############################"
+      echo -e "memory: #####################"
+      free -m
+      
+      echo -e "\n#############################"
+      echo -e "env: ########################"
+      env
+           
+      echo -e "\n#############################"
+      echo -e "Rprofile: ###################"
+      cat $(Pipeline.Workspace)/dsBase/.Rprofile
+      
+      echo -e "\n#############################"
+      echo -e "R installed.packages(): #####"
+      R -e 'installed.packages()'
+      
+      echo -e "\n#############################"
+      echo -e "R sessionInfo(): ############"
+      R -e 'sessionInfo()'
+
+      sudo apt install tree -y
+      pwd
+      echo -e "\n#############################"
+      echo -e "File tree: ##################"
+      tree $(Pipeline.Workspace)
+
+    displayName: 'Environment info'
+    condition: always()
+
+
+
+
+
